## Słonie

W Bajtockim Zoo ma się za chwilę odbyć parada, w której uczestniczyć będą wszystkie znajdujące się w nim słonie. Pracownicy zoo zachęcili już zwierzęta do ustawienia się w jednym rzędzie, gdyż zgodnie z zarządzeniem dyrektora zoo taka powinna być początkowa figura parady.

Niestety, na miejsce przybył sam dyrektor i zupełnie nie spodobała mu się wybrana przez pracowników kolejność słoni. Dyrektor zaproponował kolejność, w której według niego zwierzęta będą się najlepiej prezentować, i wydał pracownikom polecenie poprzestawiania słoni zgodnie z tą propozycją.

Aby uniknąć nadmiernego chaosu tuż przed paradą, pracownicy postanowili przestawiać słonie, zamieniając miejscami kolejno pewne pary słoni. Przestawiane zwierzęta nie muszą sąsiadować ze sobą w rzędzie. Wysiłek potrzebny do nakłonienia słonia do ruszenia się z miejsca jest wprost proporcjonalny do jego masy, a zatem wysiłek związany z zamianą miejscami dwóch słoni o masach $m_1$ oraz $m_2$ można oszacować przez $m_1 + m_2$. Jakim minimalnym wysiłkiem pracownicy mogą poprzestawiać słonie tak, aby usatysfakcjonować dyrektora?

Napisz program, który:
 * wczyta ze standardowego wejścia masy wszystkich słoni z zoo oraz aktualną i docelową kolejność słoni w rzędzie,
 * wyznaczy taki sposób poprzestawiania słoni, który prowadzi od kolejności początkowej do docelowej i minimalizuje sumę wysiłków związanych ze wszystkimi wykonanymi zamianami pozycji słoni,
 * wypisze sumę wartości tych wysiłków na standardowe wyjście.

### Wejście

Pierwszy wiersz wejścia zawiera jedną liczbę całkowitą $n$ ($2 \leq n \leq 1 000 000$), oznaczającą liczbę słoni w Bajtockim Zoo. Dla uproszczenia zakładamy, że słonie są ponumerowane od $1$ do $n$. Drugi wiersz zawiera $n$ liczb całkowitych $b_i$ ($100 \leq b_i \leq 500$ dla $1 \leq i \leq n$), pooddzielanych pojedynczymi odstępami i oznaczających masy poszczególnych słoni (wyrażone w kilogramach).

Trzeci wiersz wejścia zawiera $n$ różnych liczb całkowitych $a_i$ ($1 \leq a_i \leq n$), pooddzielanych pojedynczymi odstępami i oznaczających numery kolejnych słoni w aktualnym ustawieniu. Czwarty wiersz zawiera $n$ różnych liczb całkowitych $b_i$ ($1 \leq b_i \leq n$), pooddzielanych pojedynczymi odstępami i oznaczających numery kolejnych słoni w ustawieniu proponowanym przez dyrektora zoo. Możesz założyć, że ustawienia reprezentowane przez ciągi ($a_i$) oraz ($b_i$) są różne.

### Wyjście

Pierwszy i jedyny wiersz wyjścia powinien zawierać jedną liczbę całkowitą, oznaczającą minimalny łączny wysiłek związany z poprzestawianiem słoni, w wyniku którego z ustawienia reprezentowanego przez ($a_i$) uzyskuje się ustawienie ($b_i$).

### Losowe dane wejściowe

In [1]:
import numpy as np

N = 1000000

masses = np.random.randint(1, 1000000, N, 'int64')
old_order = np.random.permutation(N)
new_order = np.random.permutation(N)

In [2]:
display(masses)
display(old_order)
display(new_order)

array([114361, 664707, 458444, ...,  29855, 298850, 933394], dtype=int64)

array([112735, 932098, 594675, ..., 799722, 746105, 944265])

array([481647, 558320, 980862, ..., 505765, 412338, 822427])

### Uporządkowanie danych

Sortujemy nowy porządek `new_order` i masy `masses` względem starego porządku `old_order` w celu szybkiego operowania na nich.

In [3]:
perm = np.argsort(old_order)
sorted_order = new_order[perm]
sorted_masses = masses[perm]

In [4]:
sorted_order

array([451916, 146471, 664935, ..., 975210, 171704,  45649])

### Cykle

Dla każdego elementu znajdujemy jego następnik, jego następnik i tak dalej aż do momentu, gdy trafimy na pierwszy element z cyklu. Zapamiętujemy ten cykl, a jego elementy zamieniamy na $-1$ w celu zapobiegnięcia ponownego przejścia.

In [5]:
cycles = []
tmp_ord = np.copy(sorted_order)
for i in range(N):
    if tmp_ord[i] >= 0:
        cycle = [i]
        j = tmp_ord[i]
        tmp_ord[i] = -1
        while j != i:
            cycle.append(j)
            next = tmp_ord[j]
            tmp_ord[j] = -1
            j = next
        cycles.append(np.array(cycle))

cycles

[array([     0, 451916, 334481, ..., 477943, 131213, 600910]),
 array([     1, 146471, 161486, ..., 597290, 199573, 255027]),
 array([     5, 312247, 618641, ..., 448744, 278848, 323185]),
 array([     7,  19123, 421287, ...,  66249, 754295, 472766]),
 array([    10, 110729,  74758, ...,  55819,    969, 246126]),
 array([    12,  61934, 979374, ..., 430665, 396122, 861005]),
 array([    47, 987610, 656265, ..., 745260, 142302, 401905]),
 array([    53, 120945, 873368, ...,  83303, 566339, 162303]),
 array([   321, 262066, 284055, ..., 932846, 586084, 140369]),
 array([  1284, 574751, 823627, 686221, 475789, 232568, 212117, 473512,
        397040, 879669, 922692, 406017, 288169, 305594, 128861, 652707,
        654155, 460958,  72297, 667445, 239914, 521148,  73376, 701822,
        534126, 158817, 222269,  14930, 272005, 233952, 217648, 254513,
        806042, 157866, 818872, 817295, 367304, 788692, 966974, 425134,
        548301, 563367,  94616, 605674, 388110, 349177, 357688, 991221,
 

### Rozwiązywanie cykli

Każdy cykl możemy rozwiązać na dwa sposoby. Albo znajdujemy najlżejszego słonia w cyklu i zamieniamy go ze słoniem, który chce się dostać na jego miejsce, po tym z kolejnym takim słoniem i tak dalej aż do ułożenia wszystkich słoni na swoim miejscu, albo zamieniamy tego słonia z ogólnie najlżejszym i po rozwiązaniu cyklu zamieniamy je z powrotem.

Niezależnie od metody wszystkie słonie poza najlżejszymi muszą ruszyć się raz, stąd `np.sum(sorted_masses[cycle]) - sorted_masses[local_min]`. W przypadku pierwszej metody najlżejszy słoń z cyklu maszeruje $N - 1$ razy, w przypadku drugiej zaś, to ogólnie najlżejszy słoń maszeruje owe $N - 1$ razy plus zamieniamy te dwa słonie ze sobą dwukrotnie.

Po obliczeniu wyników z obu metod wybieramy tańszy wariant.

In [6]:
global_min = np.argmin(sorted_masses)
total_cost = 0

for cycle in cycles:
    if len(cycle) > 1:
        local_min = np.argmin(sorted_masses[cycle])
        rest_movement = np.sum(sorted_masses[cycle]) - sorted_masses[local_min]
        local_movement = (len(cycle) - 1) * sorted_masses[local_min]
        global_movement = (len(cycle) + 1) * sorted_masses[global_min] + 2 * sorted_masses[local_min]
        total_cost += rest_movement + min(local_movement, global_movement)

In [7]:
total_cost

499499942823